### ISSUE TITLE
"How to Contribute to Wurst-Client project" specifies incorrectly which project should have the Minecraft jar included within the Build Path

### ISSUE THREAD

**Issue by sudofox** [Wurst-Imperium/WurstClient.net#145]
I am following the instructions for 1.8, although I am using the 1.10.x repository. 

https://www.wurst-client.tk/wiki/Contributing/part4/ is the particular article. and it says this:

> Now select the Libraries tab and add all of the libraries from “YourMcpFolder/jars/libraries” again. You won’t need 1.8.jar this time, but you will need slick.jar.

For me, it does not work unless I include the 1.10.jar in the Libraries section for the Minecraft project. However, I do not need to add it to the section for the Wurst project, it seems. This is opposite of the article, which states that the Wurst project needs that file added for the Wurst project, but does not need it for the Minecraft project.

If I do it as the article specifies, I get the following output upon attempting to run the game:

```
Exception in thread "Client thread" java.lang.ExceptionInInitializerError
    at net.minecraft.util.text.translation.I18n.<clinit>(I18n.java:6)
    at net.minecraft.item.Item.getUnlocalizedNameInefficiently(Item.java:355)
    at net.minecraft.item.Item.getItemStackDisplayName(Item.java:457)
    at net.minecraft.item.ItemStack.getDisplayName(ItemStack.java:586)
    at net.minecraft.item.ItemStack.getTextComponent(ItemStack.java:1054)
    at net.minecraft.stats.StatList.initMiningStats(StatList.java:203)
    at net.minecraft.stats.StatList.init(StatList.java:143)
    at net.minecraft.init.Bootstrap.register(Bootstrap.java:547)
    at net.minecraft.client.Minecraft.<init>(Minecraft.java:373)
    at net.minecraft.client.main.Main.main(Main.java:120)
Caused by: java.lang.NullPointerException
    at java.io.Reader.<init>(Unknown Source)
    at java.io.InputStreamReader.<init>(Unknown Source)
    at org.apache.commons.io.IOUtils.readLines(IOUtils.java:986)
    at net.minecraft.util.text.translation.LanguageMap.<init>(LanguageMap.java:41)
    at net.minecraft.util.text.translation.LanguageMap.<clinit>(LanguageMap.java:27)
    ... 10 more
```

If this has somehow changed between 1.8 and 1.10, I can understand, but it would nice to see an updated version of the Contributing to Wurst article with this detail corrected, for the benefit of people trying to contribute to Wurst in the future.

Can you confirm? 

Eclipse Java Neon on Windows 10 64-bit

**Comment by Alexander01998** [comment]
The contributing tutorial on the wiki is outdated. The new version is embedded into the README file of the Wurst MC 1.10 repository: https://github.com/Wurst-Imperium/Wurst-MC-1.10#for-developers
