### ISSUE TITLE
Online error reports page doesn't work

### ISSUE THREAD

**Issue by ghost** [Wurst-Imperium/WurstClient.net#40]
When WUrst says an error occured,
it says:
[Wurst]Something went wrong with the error report.
Gist page opens, but i can't see my report in https://www.wurst-client.tk/error-reports/index.html

**Comment by Alexander01998** [comment]
That means that Wurst failed to send the report to the server (but succeeded to send it to GitHub Gist).

It is likely that this was caused by your internet connection, but if you think this is a bug, send me the stacktrace from the `Game Output` tab of the Minecraft launcher and I'll take a look at it.

**Comment by ghost** [comment]
I cant! https://github.com/Wurst-Imperium/Wurst-Client/issues/1526
@Alexander01998

**Comment by Alexander01998** [comment]
I know it doesn't save the logs, but it still appears in the `Game Output` tab.

**Comment by ghost** [comment]
No Game Output is blank too!

**Comment by rasmusolle** [comment]
The issue tracker for the repository Wurst-Client is gone. That's why.

**Comment by rasmusolle** [comment]
I think...

**Comment by ghost** [comment]
java.io.IOException: Server returned HTTP response code: 400 for URL: https://script.google.com/macros/s/AKfycbxXU9VajBGlP2t2lsfFOuCEuLKXkU7W0Udg8hlYPUHXbKX3r8U/exec?id=fc7ce5c3d626943997ec&version=2.3.2&class=tk.wurst_client.events.EventManager&action=processing events
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
    at tk.wurst_client.utils.MiscUtils.get(MiscUtils.java:150)
    at tk.wurst_client.error.gui.GuiError.actionPerformed(GuiError.java:122)
    at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:505)
    at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:591)
    at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:560)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1943)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1272)
    at net.minecraft.client.Minecraft.run(Minecraft.java:383)
    at net.minecraft.client.main.Main.main(Main.java:127)
[18:45:28] [Client thread/INFO]: [CHAT] §c[§6Wurst§c]§f §c[§4§lERROR§c]§f Something went wrong with that error report.
